name: Accessibility Test (Staging)

on:
  push:
    branches: [ master, staging ]
  pull_request:

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Pa11y on staging site with --no-sandbox flag
        run: |
          pa11y https://mathster3444staging.netlify.app/ --no-sandbox > pa11y-staging.txt
          cat pa11y-staging.txt

      - name: Upload Pa11y Report
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-staging.txt


