name: Accessibility Test

on:
  push:
    branches: [ master, staging ]
  pull_request:

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Pa11y on Staging Site
        run: |
          pa11y https://mathster3444staging.netlify.app/ > pa11y-staging.txt
          cat pa11y-staging.txt

      - name: Run Pa11y on Production Site
        run: |
          pa11y https://mathster3444staging.netlify.app/ > pa11y-production.txt
          cat pa11y-production.txt

      - name: Upload Pa11y Report 1
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report-site1
          path: pa11y-staging.txt

      - name: Upload Pa11y Report 2
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report-site2
          path: pa11y-production.txt

